### ISSUE TITLE
Invalid Image Data

### ISSUE THREAD

**Issue by Nabinda** [CHRISTOPANANJICKAL/fast_cached_network_image#7] opened 2022-12-19 11:12 UTC
Exception: Invalid image data - Image url : https://www.sefram.com/images/products/photos/hi_res/7202.jpg

I am getting an issue where image is not being decoded. Is there any solutions to it

`Exception: Invalid image data - Image url : https://www.sefram.com/images/products/photos/hi_res/7202.jpg
E/FlutterJNI(23406): Failed to decode image
E/FlutterJNI(23406): android.graphics.ImageDecoder$DecodeException: Failed to create image decoder with message 'unimplemented'Input contained an error.
E/FlutterJNI(23406): 	at android.graphics.ImageDecoder.nCreate(Native Method)
E/FlutterJNI(23406): 	at android.graphics.ImageDecoder.access$200(ImageDecoder.java:173)
E/FlutterJNI(23406): 	at android.graphics.ImageDecoder$ByteBufferSource.createImageDecoder(ImageDecoder.java:250)
E/FlutterJNI(23406): 	at android.graphics.ImageDecoder.decodeBitmapImpl(ImageDecoder.java:1847)
E/FlutterJNI(23406): 	at android.graphics.ImageDecoder.decodeBitmap(ImageDecoder.java:1840)
E/FlutterJNI(23406): 	at io.flutter.embedding.engine.FlutterJNI.decodeImage(FlutterJNI.java:524)
E/FlutterJNI(23406): Failed to decode image
E/FlutterJNI(23406): android.graphics.ImageDecoder$DecodeException: Failed to create image decoder with message 'unimplemented'Input contained an error.
E/FlutterJNI(23406): 	at android.graphics.ImageDecoder.nCreate(Native Method)
E/FlutterJNI(23406): 	at android.graphics.ImageDecoder.access$200(ImageDecoder.java:173)
E/FlutterJNI(23406): 	at android.graphics.ImageDecoder$ByteBufferSource.createImageDecoder(ImageDecoder.java:250)
E/FlutterJNI(23406): 	at android.graphics.ImageDecoder.decodeBitmapImpl(ImageDecoder.java:1847)
E/FlutterJNI(23406): 	at android.graphics.ImageDecoder.decodeBitmap(ImageDecoder.java:1840)
E/FlutterJNI(23406): 	at io.flutter.embedding.engine.FlutterJNI.decodeImage(FlutterJNI.java:524)`

**Comment by gionlime** [comment] 2022-12-29 02:56
> Exception: Invalid image data - Image url : https://www.sefram.com/images/products/photos/hi_res/7202.jpg
> 
> I am getting an issue where image is not being decoded. Is there any solutions to it
> 
> `Exception: Invalid image data - Image url : https://www.sefram.com/images/products/photos/hi_res/7202.jpg E/FlutterJNI(23406): Failed to decode image E/FlutterJNI(23406): android.graphics.ImageDecoder$DecodeException: Failed to create image decoder with message 'unimplemented'Input contained an error. E/FlutterJNI(23406): at android.graphics.ImageDecoder.nCreate(Native Method) E/FlutterJNI(23406): at android.graphics.ImageDecoder.access$200(ImageDecoder.java:173) E/FlutterJNI(23406): at android.graphics.ImageDecoder$ByteBufferSource.createImageDecoder(ImageDecoder.java:250) E/FlutterJNI(23406): at android.graphics.ImageDecoder.decodeBitmapImpl(ImageDecoder.java:1847) E/FlutterJNI(23406): at android.graphics.ImageDecoder.decodeBitmap(ImageDecoder.java:1840) E/FlutterJNI(23406): at io.flutter.embedding.engine.FlutterJNI.decodeImage(FlutterJNI.java:524) E/FlutterJNI(23406): Failed to decode image E/FlutterJNI(23406): android.graphics.ImageDecoder$DecodeException: Failed to create image decoder with message 'unimplemented'Input contained an error. E/FlutterJNI(23406): at android.graphics.ImageDecoder.nCreate(Native Method) E/FlutterJNI(23406): at android.graphics.ImageDecoder.access$200(ImageDecoder.java:173) E/FlutterJNI(23406): at android.graphics.ImageDecoder$ByteBufferSource.createImageDecoder(ImageDecoder.java:250) E/FlutterJNI(23406): at android.graphics.ImageDecoder.decodeBitmapImpl(ImageDecoder.java:1847) E/FlutterJNI(23406): at android.graphics.ImageDecoder.decodeBitmap(ImageDecoder.java:1840) E/FlutterJNI(23406): at io.flutter.embedding.engine.FlutterJNI.decodeImage(FlutterJNI.java:524)`

please use version: fast_cached_network_image: ^0.0.4

**Comment by stevenosse** [comment] 2023-01-31 14:40
Hello

Please, can you share more details ? (flutter/dart version, device infos, etc....)
I'm not able to reproduce this.

**Comment by CHRISTOPANANJICKAL** [comment] 2024-02-02 16:33
Closing  due to inavtivity

**Closed by CHRISTOPANANJICKAL** 2024-02-02 16:33 UTC
Labels: question
