### ISSUE TITLE
dio 

### ISSUE THREAD

**Issue by MrErkinjon** [CHRISTOPANANJICKAL/fast_cached_network_image#44] opened 2023-12-27 08:43 UTC
I/flutter (10709): Source stack:
I/flutter (10709): #0      DioMixin.fetch (package:dio/src/dio_mixin.dart:488:35)
I/flutter (10709): #1      DioMixin.request (package:dio/src/dio_mixin.dart:483:12)
I/flutter (10709): #2      DioMixin.get (package:dio/src/dio_mixin.dart:61:12)
I/flutter (10709): #3      _FastCachedImageState._loadAsync (package:fast_cached_network_image/src/fast_cached_image.dart:305:12)

**Comment by Padi142** [comment] 2023-12-29 23:45
Could you provide a bit more context on what you tried to do ?

**Comment by MrErkinjon** [comment] 2024-01-02 11:28
After I connect to the project, such an error appears in the log

**Comment by Padi142** [comment] 2024-01-02 13:11
Are you sure you are entering  a valid URL of an image to the widget ? Provide a code sample please

**Comment by MrErkinjon** [comment] 2024-01-03 04:31
"https://static.vecteezy.com/system/resources/previews/005/337/799/original/icon-image-not-found-free-vector.jpg"
 
 
 
  static Widget buildNetworkImageSignUp(String? url, Widget defIcon,
      {double? height, double? width, BoxFit? fit, double? radius, double? paddingPlaceHolder}) {
    radius ??= 16;
    paddingPlaceHolder ??= 8;
    return ClipRRect(
      borderRadius: BorderRadius.circular(radius),
      child: FastCachedImage(
        url: url ?? "",
        height: height,
        width: width,
        fit: fit,
        errorBuilder: (context, error, stackTrace) => Center(
          child: Padding(
            padding: EdgeInsets.all(paddingPlaceHolder!),
            child: defIcon,
          ),
        ),
        loadingBuilder: (context, progress) {
          debugPrint('Progress: ${progress.isDownloading} ${progress.downloadedBytes} / ${progress.totalBytes}');
          return Container(
            color: colorYellow,
            child: Stack(
              alignment: Alignment.center,
              children: [
                if (progress.isDownloading && progress.totalBytes != null)
                  // Center(
                  //   child: Padding(
                  //     padding: const EdgeInsets.all(8.0),
                  //     child: AutoSizeText(
                  //         '${progress.downloadedBytes ~/ 1024} / ${progress.totalBytes! ~/ 1024} kb',
                  //         style: const TextStyle(color: colorPrimary)),
                  //   ),
                  // ),
                  SizedBox(width: 120, height: 120, child: CircularProgressIndicator(color: colorPrimary, value: progress.progressPercentage.value)),
              ],
            ),
          );
        },
      ),
    );
  }

**Comment by MrErkinjon** [comment] 2024-01-03 04:32
main 
//init
  await FastCachedImageConfig.init(clearCacheAfter: const Duration(days: 1));

**Comment by CHRISTOPANANJICKAL** [comment] 2024-03-13 10:22
https://github.com/CHRISTOPANANJICKAL/fast_cached_network_image/assets/58786637/70a546c0-2218-4fc3-a77a-61a266d9954a

Closing this issue since it cannot be reproduced

**Closed by CHRISTOPANANJICKAL** 2024-03-13 10:22 UTC
