### ISSUE TITLE
in web issue found 

### ISSUE THREAD

**Issue by sunil-singh-chaudhary** [CHRISTOPANANJICKAL/fast_cached_network_image#48] opened 2024-03-11 07:19 UTC
DioException [connection error]: The connection errored: The XMLHttpRequest onError callback was called. This typically indicates an error on the network layer. This indicates an error which most likely cannot be solved by the library. - Image url : https://astroway.diploy.in/public/storage/images/banner_141709053704.png
DioException [connection error]: The connection errored: The XMLHttpRequest onError callback was called. This typically indicates an error on the network layer. This indicates an error which most likely cannot be solved by the library. - Image url : https://astroway.diploy.in/public/storage/images/banner_191709050155.png

why it is showing this error while using CachedNetworkImage it is working fine previouslly my code is 

in main.dart
  await FastCachedImageConfig.init();

and in widget

                                      child: FastCachedImage(
                                        url:
                                            '${global.imgBaseurl}${homeController.bannerList[index].bannerImage}',
                                        fit: BoxFit.cover,
                                        fadeInDuration:
                                            const Duration(seconds: 1),
                                        errorBuilder:
                                            (context, exception, stacktrace) {
                                          return Text(stacktrace.toString());
                                        },
                                        loadingBuilder: (context, progress) {
                                          return Container(
                                            color: Colors.yellow,
                                            child: Stack(
                                              alignment: Alignment.center,
                                              children: [
                                                if (progress.isDownloading &&
                                                    progress.totalBytes != null)
                                                  Text(
                                                      '${progress.downloadedBytes ~/ 1024} / ${progress.totalBytes! ~/ 1024} kb',
                                                      style: const TextStyle(
                                                          color: Colors.red)),
                                                SizedBox(
                                                    width: 120,
                                                    height: 120,
                                                    child: CircularProgressIndicator(
                                                        color: Colors.red,
                                                        value: progress
                                                            .progressPercentage
                                                            .value)),
                                              ],
                                            ),
                                          );
                                        },
                                      ),

**Comment by CHRISTOPANANJICKAL** [comment] 2024-03-11 10:25
Closing since its duplicate of #19

**Closed by CHRISTOPANANJICKAL** 2024-03-11 10:25 UTC
